#!/bin/sh

# Set these paths appropriately

BIN=/home/thomas/workspace/Emotions/Ttagger/bin
CMD=/home/thomas/workspace/Emotions/Ttagger/cmd
LIB=/home/thomas/workspace/Emotions/Ttagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
