#!/bin/sh

# Set these paths appropriately

BIN=/home/thomas/workspace/Emotions/Ttagger/bin
CMD=/home/thomas/workspace/Emotions/Ttagger/cmd
LIB=/home/thomas/workspace/Emotions/Ttagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
